### ISSUE TITLE
Read frames from Twitch

### ISSUE THREAD

**Issue by andrewda** [andrewda/frc-score-detection#4]

**Comment by snowsignal** [comment]
One problem we might run into (as I discovered while testing) is that we need an API token for Twitch, and it has to be run through a user. If we are making constant requests, it might look suspicious. Also, the API token would have to be different for each installation, or Twitch might deactivate that token/user if it detects a bunch of requests.

**Comment by andrewda** [comment]
Yea we would need to add an API key parameter.
